name: Static Scan

on:
  workflow_dispatch:

run-name: Static Scan - ${{ github.ref_name }}

permissions:
  contents: read

jobs:
  sast-scan:
    name: Static Analysis Security Testing (SAST) Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup Maven Dependency Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Generate CycloneDX SBOM
        run: mvn org.cyclonedx:cyclonedx-maven-plugin:2.7.9:makeAggregateBom

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-cyclonedx.json
          path: target/bom.json

      - name: Grype Dependency Scan
        id: scan
        uses: anchore/scan-action@dccc91b95904c40fb7585875d9ce46eeb3b497df
        with:
          path: .
          sbom: target/bom.json
          fail-build: false
          fail-on-severity: "medium"
          output-format: "table"
          output-file: "grype-report.txt"
