name: Workflow Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflow-scan:
    name: Workflow Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"

      - name: Install zizmor
        run: pip install zizmor

      - name: Run zizmor on Workflow
        run: |
          zizmor --offline .
